/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "stm32f4xx.h"
#include "system_stm32f4xx.h"

#include "uart.h"
#include "lis3dsh.h"
#include "led.h"
#include "i2c_lcd.h"
#include "i2c.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int xCal = 0, yCal = 0, zCal = 0;

int main(void)
{
	char str[32];
	int ret;
	LIS_Data val;
	SystemInit();
	LedInit(LED_GREEN);
	LedInit(LED_ORANGE);
	LedInit(LED_RED);
	LedInit(LED_BLUE);
	LcdInit();
	UartInit(BAUD_9600);
	UartPuts("LIS3DSH Accel Demo!\r\n");
	LIS_Init();
	DelayMs(1000);

	LIS_DRdy_Calib();

	UartPuts("Calibration Done.\r\n");
	sprintf(str, "X=%d, Y=%d, Z=%d\r\n", xCal, yCal, zCal);
	UartPuts(str);

	DelayMs(3000);

	while(1) {
		ret = LIS_DRdy();
		if(ret) {
			//int xPLimit = 250, xMLimit = 50, yPLimit = 150, yMLimit = 0, zPLimit = 250, zMLimit = 100;

			val = LIS_GetData();
			sprintf(str, "X=%d, Y=%d\r", val.x, val.y);
			LcdPuts(LCD_LINE1, str);
			sprintf(str, "Z=%d\r\n", val.z);
			LcdPuts(LCD_LINE2, str);

			UartPuts(str);
			DelayMs(500);

		}
	}
	return 0;
}



